In [90]:
import pandas as pd
fp = 'C:\\Users\\ami12\\Downloads\\train.csv'

In [91]:
data = pd.read_csv(fp)

In [92]:
data.describe()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,7124,7124,7124,7124,7124,7124,7124,7124,7124,7124,...,7124,7124,7124,7124,7124,7124,7124,7124,7124,7124
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,3695,3199,2830,1997,4148,3096,6942,5970,4914,1512,...,4327,3943,3845,7124,6949,6569,3495,2082,3547,2768

In [93]:
y = data['class']

In [94]:
y.head()

0    e
1    e
2    e
3    p
4    p
Name: class, dtype: object

In [95]:
features = ['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
        'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
        'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
        'stalk-surface-below-ring', 'stalk-color-above-ring',
        'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
        'ring-type', 'spore-print-color', 'population', 'habitat']

In [96]:
x = pd.get_dummies(data[features])

In [97]:
x.head()

,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,cap-surface_y,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,0,0,0,0,0,1,0,0,0,1,...,0,1,0,1,0,0,0,0,0,0
1,0,0,0,0,0,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,1,...,0,1,0,1,0,0,0,0,0,0
3,0,0,1,0,0,0,1,0,0,0,...,0,1,0,1,0,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=7456)

In [100]:
from sklearn.tree import DecisionTreeClassifier

In [101]:
model = DecisionTreeClassifier(random_state=1)

In [102]:
model.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1, splitter='best')

In [103]:
from sklearn.metrics import classification_report

In [104]:
rep = classification_report(y_test,model.predict(X_test), target_names=['e','p'])

In [105]:
print(rep)

              precision    recall  f1-score   support

           e       1.00      1.00      1.00      1239
           p       1.00      1.00      1.00      1112

    accuracy                           1.00      2351
   macro avg       1.00      1.00      1.00      2351
weighted avg       1.00      1.00      1.00      2351

In [106]:
tfp = 'C:\\Users\\ami12\\Downloads\\Q1_Mushroom_test.csv'

In [107]:
test = pd.read_csv(tfp)

In [108]:
test.head()

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,f,y,n,f,s,f,c,n,b,t,...,s,w,p,p,w,o,e,w,v,d
1,x,s,e,f,s,f,c,n,b,t,...,s,p,w,p,w,o,e,w,v,l
2,f,s,w,f,n,f,w,b,h,t,...,f,w,w,p,w,o,e,n,a,g
3,b,y,y,t,l,f,c,b,w,e,...,s,w,w,p,w,o,p,k,n,m
4,f,f,g,f,n,f,w,b,p,t,...,f,w,w,p,w,o,e,n,a,g

In [109]:
xt = pd.get_dummies(test[features])

In [110]:
xt.head()

,cap-shape_b,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,cap-surface_y,cap-color_b,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,0,1,0,0,0,0,0,0,1,0,...,0,1,0,1,0,0,0,0,0,0
1,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0
2,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
3,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
4,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [112]:
test.describe()

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,...,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,5,4,10,2,9,2,2,2,12,2,...,4,9,9,1,4,3,5,9,6,7
top,x,y,n,f,n,f,c,b,b,t,...,s,w,w,p,w,o,p,w,v,d
freq,457,414,287,600,432,972,842,698,216,563,...,609,521,539,1000,975,919,473,306,493,380

In [113]:
data.describe()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,7124,7124,7124,7124,7124,7124,7124,7124,7124,7124,...,7124,7124,7124,7124,7124,7124,7124,7124,7124,7124
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,3695,3199,2830,1997,4148,3096,6942,5970,4914,1512,...,4327,3943,3845,7124,6949,6569,3495,2082,3547,2768

The test set doesnt have any mushroom with cap shape c, so the below addition

In [114]:
xt.insert(1, "cap-shape_c", [0]*1000, True)

In [115]:
xt.describe()

,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,cap-surface_y,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
count,1000.000000,1000.0,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.00000,1000.000000
mean,0.053000,0.0,0.385000,0.098000,0.007000,0.457000,0.282000,0.001000,0.303000,0.414000,...,0.149000,0.493000,0.213000,0.380000,0.265000,0.1020,0.027000,0.157000,0.04600,0.023000
std,0.224146,0.0,0.486839,0.297463,0.083414,0.498397,0.450198,0.031623,0.459785,0.492795,...,0.356267,0.500201,0.409633,0.485629,0.441554,0.3028,0.162164,0.363983,0.20959,0.149978
min,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.00000,0.000000
25%,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.00000,0.000000
50%,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.00000,0.000000
75%,0.000000,0.0,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,...,0.000000,1.000000,0.000000,1.000000,1.000000,0.0000,0.000000,0.000000,0.00000,0.000000
max,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.00000,1.000000

In [116]:
prediction = model.predict(xt)

In [124]:
for i in range(1000):
    print(prediction[i])

p
p
e
e
e
p
p
e
p
p
p
p
e
e
p
e
p
e
e
p
e
p
p
p
e
p
p
p
e
e
e
e
e
p
e
e
p
e
e
p
e
p
e
e
p
p
e
e
p
p
e
p
p
e
e
p
p
p
p
p
e
e
p
e
p
p
p
e
p
e
p
e
p
p
p
e
e
e
p
p
p
p
p
e
e
p
e
e
p
e
e
p
e
p
p
e
p
p
e
p
e
p
e
p
p
p
p
p
e
e
e
e
e
p
e
p
p
e
e
e
p
p
p
e
e
e
e
e
p
p
e
p
p
e
e
e
p
e
p
p
p
p
p
e
p
p
p
e
p
p
e
p
p
p
e
e
p
p
e
e
e
e
e
p
e
p
e
p
e
p
e
e
p
e
p
p
e
e
p
e
e
e
p
e
e
p
p
p
p
p
e
p
e
e
e
e
p
p
p
p
p
p
e
p
e
p
e
e
e
e
e
e
e
e
p
p
e
p
p
e
e
p
p
p
e
p
p
e
e
e
p
p
p
e
p
e
e
e
p
p
e
e
p
e
p
e
p
e
p
p
p
e
p
p
p
e
p
p
e
p
e
p
e
e
p
p
p
e
p
p
e
e
p
e
e
e
p
e
e
e
p
e
e
p
e
e
e
e
e
e
e
e
p
p
e
e
p
e
e
e
p
p
p
e
p
e
p
e
p
p
e
p
e
p
p
p
e
p
e
p
e
p
p
e
e
p
e
p
e
e
e
p
e
p
p
e
p
p
p
e
e
e
p
e
p
e
e
p
e
e
p
p
p
e
e
e
p
p
p
p
e
p
p
e
e
p
p
p
e
p
p
e
p
e
p
p
e
e
e
e
e
p
e
e
p
e
p
e
p
e
p
e
p
p
e
e
e
e
p
e
p
e
e
e
e
e
p
p
e
p
e
p
p
e
e
e
p
p
e
e
e
p
p
p
e
e
p
e
p
p
e
e
p
p
e
e
p
p
e
p
e
e
p
e
e
e
p
p
p
p
e
e
e
p
p
e
p
p
e
e
e
p
p
e
p
e
e
e
e
e
e
p
e
p
e
e
e
e
e
p
p
e
e
p
p
e
e
p
p
p
e
e
p
p
p
e
p
e
e
p
p
e
e
e
e
p
p
p
e
e
e
e
e
p
p
e
p
p
p
e
e
p
p
p
e
p
p
e
e
p
e
e
p
p
p
e
p
p
e
e
e
e
e
e
e
e
e
e
e
p
e
e
p
e
e
e
p
e
p
e
e
e
p
e
p
e
p
e
e
e
p
p
p
e
p
p
e
p
p
e
e
e
e
e
p
p
e
p
e
p
e
e
p
p
p
e
p
p
p
e
e
e
p
p
e
p
p
e
p
p
p
e
e
e
p
e
p
e
p
p
e
e
e
e
p
e
e
p
p
p
e
p
p
p
e
p
p
e
e
p
e
e
e
p
p
p
p
p
p
e
p
p
e
e
e
p
p
p
p
e
e
e
e
p
e
p
p
p
e
e
e
e
p
p
e
e
p
e
p
e
e
e
e
p
e
e
p
e
p
p
p
p
e
p
p
p
e
p
p
p
e
e
e
p
p
e
p
p
e
e
p
p
e
p
e
e
e
e
e
p
e
e
e
e
p
p
e
p
p
p
e
p
e
p
p
p
p
e
e
e
e
e
e
p
e
p
e
p
p
e
p
p
e
p
e
e
e
p
p
e
p
e
e
p
e
e
e
e
p
p
e
e
p
e
e
p
e
e
e
e
p
p
p
e
e
p
e
e
e
e
p
p
e
e
e
p
p
p
p
e
e
e
p
e
e
p
e
p
e
e
p
p
p
e
p
p
p
p
e
p
p
e
e
p
p
p
p
e
p
p
e
p
e
e
e
p
e
p
p
e
p
p
e
e
e
p
p
e
p
p
p
e
p
p
p
e
e
e
e
p
e
p
p
e
e
p
e
p
e
p
e
p
p
p
e
e
p
e
e
e
p
e
p
e
p
e
p
p
p
p
e
e
e
p
e
p
e
e
p
e
p
e
e
e
p
p
p
p
e
e
p
p
p
p
e
e
e
p
e
p
e
p
p
p
e
p
e
e
p
e
p
p
e
e
p
e
e
e
p
e
e
p
e
p
e
p
e
e
p
p
p
p
e
p
p
p
e
e
e
e
e
p
p
p
e
e
p
e
e
e
p
p
p
e
e
e
p
e
e
e
p
e
e
p
p
p
e
p
e
p
e
p
p
e
p
p
e
p
e
p